import type { Metadata } from "next";
import { Nav } from "@/components/ui/nav";
import { Footer } from "@/components/ui/footer";
import { GhostButton } from "@/components/ui/ghost-button";

export const metadata: Metadata = {
  title: "AI Tool to Find Marketers for Your Product",
  description:
    "Vibr scans LinkedIn to find marketers matching your product's sector, ranks them by relevance, and generates personalized cold outreach emails. Find growth marketers for your SaaS startup with AI.",
  alternates: {
    canonical: "https://vibr-ai.com/find-marketers",
  },
  openGraph: {
    title: "AI Tool to Find Marketers for Your Product",
    description:
      "Find growth marketers for your SaaS startup with AI. Vibr scans LinkedIn, ranks marketers by relevance, and generates personalized outreach emails.",
    type: "website",
  },
};

export default function FindMarketersPage() {
  return (
    <main className="bg-background min-h-screen">
      <Nav />

      {/* Hero */}
      <section className="pt-40 pb-24 px-6">
        <div className="max-w-[900px] mx-auto text-center">
          <h1 className="font-heading font-light text-5xl md:text-7xl text-foreground leading-tight">
            AI Tool to Find Marketers{" "}
            <br />
            for Your Product
          </h1>
          <p className="mt-8 font-body font-light text-lg text-muted max-w-[600px] mx-auto">
            You built the product. Now you need someone to grow it. Vibr uses AI
            to find marketers who already understand your niche and ranks them by
            how well they fit.
          </p>
          <div className="mt-8">
            <GhostButton href="/onboarding">
              Find your marketer
            </GhostButton>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-24 px-6 border-t border-[#222]">
        <div className="max-w-[900px] mx-auto">
          <h2 className="font-heading font-light text-3xl md:text-4xl text-foreground">
            AI Marketer Matching Powered by LinkedIn Data
          </h2>
          <p className="mt-6 font-body font-light text-base text-muted leading-relaxed">
            Vibr takes your product description, target audience, and sector,
            then scans LinkedIn for marketers whose experience aligns with your
            space. It looks at past roles, industries, content they have
            published, and the types of products they have grown before.
          </p>
          <p className="mt-4 font-body font-light text-base text-muted leading-relaxed">
            Each candidate is scored on relevance so you spend your time talking
            to people who are most likely to say yes — not cold-emailing
            hundreds of strangers.
          </p>
        </div>
      </section>

      {/* Ranking */}
      <section className="py-24 px-6 border-t border-[#222]">
        <div className="max-w-[900px] mx-auto">
          <h2 className="font-heading font-light text-3xl md:text-4xl text-foreground">
            Find Growth Marketers for Your SaaS Startup
          </h2>
          <p className="mt-6 font-body font-light text-base text-muted leading-relaxed">
            Whether you are launching a developer tool, a B2B platform, or a
            consumer app, Vibr surfaces marketers with track records in your
            specific vertical. The ranking system weighs sector match, seniority,
            audience overlap, and recent activity to give you a shortlist you
            can act on immediately.
          </p>
          <p className="mt-4 font-body font-light text-base text-muted leading-relaxed">
            No more guesswork. No more scrolling through LinkedIn for hours. You
            get a curated list of five to ten marketers, each with a profile
            summary and a relevance score.
          </p>
        </div>
      </section>

      {/* Outreach */}
      <section className="py-24 px-6 border-t border-[#222]">
        <div className="max-w-[900px] mx-auto">
          <h2 className="font-heading font-light text-3xl md:text-4xl text-foreground">
            Personalized Cold Outreach Emails Generated by AI
          </h2>
          <p className="mt-6 font-body font-light text-base text-muted leading-relaxed">
            Once you pick the marketers you want to reach out to, Vibr drafts a
            personalized cold email for each one. The email references their
            background, explains why your product is relevant to their
            expertise, and proposes a clear next step.
          </p>
          <p className="mt-4 font-body font-light text-base text-muted leading-relaxed">
            You review, edit if you want, and send. The entire flow — from
            finding marketers to sending the first message — takes minutes
            instead of days.
          </p>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6 border-t border-[#222]">
        <div className="max-w-[900px] mx-auto text-center">
          <h2 className="font-heading font-light text-3xl md:text-4xl text-foreground">
            Stop Searching. Start Reaching Out.
          </h2>
          <p className="mt-6 font-body font-light text-base text-muted max-w-[520px] mx-auto">
            Describe your product and let Vibr find the right people to grow it.
          </p>
          <div className="mt-8">
            <GhostButton href="/onboarding">Start building</GhostButton>
          </div>
        </div>
      </section>

      {/* Internal links */}
      <section className="py-16 px-6 border-t border-[#222]">
        <div className="max-w-[900px] mx-auto">
          <p className="font-body text-xs text-muted uppercase tracking-[0.2em] mb-6">Explore more</p>
          <div className="flex flex-wrap gap-8">
            <a href="/ideas" className="font-body text-sm text-foreground hover:underline">AI Idea Generator</a>
            <a href="/local-ide" className="font-body text-sm text-foreground hover:underline">Local AI IDE</a>
            <a href="/outreach" className="font-body text-sm text-foreground hover:underline">AI Outreach</a>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
